/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package cbr_cacingan.user;

import static cbr_cacingan.user.Solusi.arg1;
import static cbr_cacingan.user.Solusi.arg2;
import static cbr_cacingan.user.Solusi.arg3;
import javax.swing.JFrame;

/**
 *
 * @author HP
 */
public class Pencegahan extends javax.swing.JFrame {

    String penyakit;
    String kode;
    public static String arg1, arg2, arg3;
    String openHtml = "<HTML>";
    String closeHtml = "</HTML>";
    String openParag = "<P style=\"text-align: justify \">";
    String closeParag = "</P>";
    
    public Pencegahan(String kodePenyakit, String namaPenyakit, String pencegahan) {
        initComponents();
        kode = kodePenyakit;
        penyakit = namaPenyakit;
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        setTitle("Pencegahan " + namaPenyakit);
        setState();
        setLocationRelativeTo(null);
    }
    
     public void setState() {

        try {
            labTitle.setText("Pencegahan Penyakit " + penyakit);
            labTabel.setText(openHtml+openParag + arg3 + closeParag+closeHtml);
//            labTabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cbr_cacingan/assets/"+kode+".png"))); 
        } catch (Exception e) {
            labTitle.setText("Pencegahan Penyakit " + penyakit);
//            labTabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cbr_cacingan/assets/P01.png"))); 
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labTitle = new javax.swing.JLabel();
        labTabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(915, 548));

        jPanel1.setBackground(new java.awt.Color(255, 102, 153));
        jPanel1.setPreferredSize(new java.awt.Dimension(915, 548));

        labTitle.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labTitle.setForeground(new java.awt.Color(255, 255, 255));
        labTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labTitle.setText("Tabel Pencegahan Penyakit");

        labTabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labTabel.setForeground(new java.awt.Color(255, 255, 255));
        labTabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(182, 182, 182)
                .addComponent(labTabel, javax.swing.GroupLayout.DEFAULT_SIZE, 551, Short.MAX_VALUE)
                .addGap(182, 182, 182))
            .addComponent(labTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(labTabel, javax.swing.GroupLayout.DEFAULT_SIZE, 395, Short.MAX_VALUE)
                .addGap(72, 72, 72))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pencegahan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pencegahan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pencegahan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pencegahan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        arg1 = args[0];
        arg2 = args[1];
        arg3 = args[2];
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pencegahan(arg1, arg2, arg3).setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labTabel;
    private javax.swing.JLabel labTitle;
    // End of variables declaration//GEN-END:variables
}
